#lang racket
(require framework)
(require racket/gui racket/runtime-path)
(define-runtime-path scrbl-indentation.scrbl "scrbl-indentation.scrbl")
(require "scribble-indentation.rkt")
(define f (new frame% [label ""] [width 800] [height 600]))
(define t (new racket:text%))
(define ec (new editor-canvas% [parent f] [editor t]))
(define k (new keymap%))
(define (reindent-paragraph t evt)
  (define sp (send t get-start-position))
  (when (= sp (send t get-end-position))
    (printf "calling ~s\n" (list t sp 60))
    (paragraph-indentation t sp 60)))
(send k add-function "reindent-paragraph" reindent-paragraph)
(send k map-function "esc;q" "reindent-paragraph")
(send k map-function "c:q" "reindent-paragraph")
(send k add-function "save" (λ (t evt) (send t save-file)))
(send k map-function "d:s" "save")
(send t set-keymap k)
(send f show #t)
(send t load-file scrbl-indentation.scrbl)
